---
- hosts: all
  tasks:
    - debug: var=groups
    - debug: var=ansible_all_ipv4_addresses

    - name: Install docker 1.12
      shell: >
        curl -fsSL https://get.docker.com/ | sh

    - name: Start docker service
      become: yes
      become_user: root
      service: name=docker state=started enabled=true

- hosts: managers[0]
  tasks:
    - debug: msg="Starting primary swarm manager"
    # Start primary swarm manager

    # Create overlay network

    # Save manager and worker tokens as facts

- hosts: managers[1:]
  tasks:
    - debug: msg="Starting secondary swarm managers"
    # Start secondary swarm managers



- hosts: workers
  tasks:
    - debug: msg="Starting swarm workers"
    # Join swarm workers