---

- name: Build collectd container
  run_once: true
  become: yes
  become_user: root
  shell: >
    docker build -t collectd .
  args:
    chdir: /vagrant/collectd

- name: Get existing services
  shell: >
    docker service ls --filter name=collectd | tail -n +2
  register: collectd_result

#- name: load collectd image
#  become: yes
#  become_user: root
#  shell: >
#    docker load -i /vagrant/collectd-docker.tar
#  when: inventory_hostname != "{{ groups['managers'][0] }}"

#- name: Clean up collectd image
#  run_once: true
#  become: yes
#  become_user: root
#  file: path=/vagrant/collectd-docker.tar state=absent
#  delegate_to: "{{ groups['managers'][0] }}"

# Could possibly be an issue with the --priviledged flag which is not available
# for services
- name: Running collectd container
  become: yes
  become_user: root
  shell: >
    docker service create \
      --name collectd \
      --mode global \
      --network appnet \
      --mount type=bind,src=/vagrant/collectd/root/etc/collectd/,dst=/etc/collectd/ \
      --mount type=bind,src=/vagrant/collectd/root/etc/collectd.d/,dst=/etc/collectd.d/ \
      --mount type=bind,src=/proc,dst=/mnt/proc,readonly \
      collectd
  when: "'collectd' not in collectd_result.stdout"
