- name: Check existence of docker
  stat: path={{ docker_service }}
  register: install_result

- name: Install docker 1.12
  shell: >
    curl -fsSL https://get.docker.com/ | sh
  when: not install_result.stat.exists

- name: Start docker service
  service: name=docker state=started enabled=true

- name: Check the docker status
  no_log: true
  shell: >
    echo -e "GET /info HTTP/1.0\r\n" | nc -U /var/run/docker.sock | tail -n +6 | python -m json.tool
  register: docker_result

- set_fact:
    docker_info: "{{ docker_result.stdout | from_json }}"

- name: Start docker-ui globally (needs work)
  run_once: true
  shell: >
    docker service create \
      --name docker-ui \
      --mount type=bind,target=/var/run/docker.sock,src=/var/run/docker.sock \
      -p 9000:9000/tcp \
      --network appnet \
      --mode global \
      uifd/ui-for-docker \
  delegate_to: "{{ groups['managers'][0] }}"
  tags:
    - docker-ui