---
- hosts: managers[0]
  become: yes
  become_user: root
  tasks:
    - name: install dependencies
      yum: name={{ item }} state=latest
      with_items:
        - python-pip
        - bind-utils

    - name: install docker python dependencies
      pip: name={{ item }}
      with_items:
        - pyyaml
        - docker-py
        - docker-compose

    - name: Get networks
      shell: >
        docker network ls --filter name={{ item }}$ | tail -n +2
      with_items:
        - appnet
      register: network_result

    - set_fact:
        docker_current_networks: "{{ network_result.results | map(attribute='stdout') | list | join(' ') }}"

    - name: Create overlay networks
      shell: >
        docker network create -d overlay {{ item }}
      when: item not in docker_current_networks
      with_items:
        - appnet

    - name: Get existing services
      shell: >
        docker service ls --filter name={{ item.name }} | tail -n +2
      with_items: "{{ docker_services }}"
      register: services_result

    - set_fact:
        docker_current_services: "{{ services_result.results | map(attribute='stdout') | list | join(' ') }}"

    # Use task include so we can pause between starting up services.
    - include: service.yml service_dict={{ item }}
      with_items: "{{ docker_services }}"

# --------------------------------------------------
# docker_service has a number of issues that need looking
# into
#   1. compose doesn't work with swarm - Major blocker
# --------------------------------------------------
#    - name: Start initial demo services
#      docker_service:
#        project_name: demo
#        tls: yes
#        definition:
#          version: '2'
#          networks:
#            app:
#              driver: overlay
#          services:
#            redis:
#              image: redis:3.0.7-alpine
#              networks:
#                - app
#     register: compose_result
#
#    - debug: var=compose_result
